spring:
  application:
    name: schfme-content-api 
server:
  port: ${PORT:5000}
app:
  environment: test
  parameter-names:
    api-keys-path: "/${spring.application.name}/${app.environment}/api-keys/"
    cluster-name: "/schfme/${app.environment}/database/connection/cluster-name"
    host: "/schfme/${app.environment}/database/connection/host"
    database-name: "/schfme/${app.environment}/database/name"
    service-name: "/schfme/${app.environment}/database/service/name"
    service-password: "/schfme/${app.environment}/database/service/password"
---

spring:
  config:
    activate:
      on-profile: test
---
spring:
  config:
    activate:
      on-profile: prod
app:
  environment: prod